title: ECMAScript2022
date: 2023.05.26
tags: [ECMAScript规范, JavaScript]
categories: ECMAScript规范
---
在 ECMAScript2022 中，只有8个新增特性Class Fields、RegExp Match Indices、Top-level await、Ergonomic brand checks for Private Fields、.at()、Accessible Object.prototype.hasOwnProperty、Class Static Block、Error Cause。具体每年新增的特性，可以在这个[finished-proposals](https://github.com/tc39/proposals/blob/main/finished-proposals.md)看到.
<!--more-->
## 1 Class Fields
这个特性其实是最早从2017年就开始提的class字段，后来又逐渐的添加了私有字段、私有方法等特性进来，所以一直拖到2022年才最终完稿。
### 公共字段
```javascript
class Test {
  name = 'test-name';
  #fn(){
    this.a = 1
  }
  get #x() { return this.#xValue; }
  set #x(value) {
    this.#xValue = value;
    window.requestAnimationFrame(this.#render.bind(this));
  }
}
```
### 私有字段/方法/访问器
```javascript
class Test {
  #name = 'test-name';
  #fn(){
    this.a = 1
  }
  get #x() { return this.#xValue; }
  set #x(value) {
    this.#xValue = value;
    window.requestAnimationFrame(this.#render.bind(this));
  }
}
```
### 静态字段、静态私有字段和方法

```javascript
class Test {
  static name = 1;
  static #name1 = 'test-name';
  static #fn(){
    this.a = 1
  }
}
```

## 2 [RegExp Match Indices](https://github.com/tc39/proposal-regexp-match-indices)
在正则表达式中新增了一个`/d`的flag
```javascript
const re1 = /a+(?<Z>z)?/d;

// indices are relative to start of the input string:
const s1 = "xaaaz";
const m1 = re1.exec(s1);
m1.indices[0][0] === 1;
m1.indices[0][1] === 5;
s1.slice(...m1.indices[0]) === "aaaz";

m1.indices[1][0] === 4;
m1.indices[1][1] === 5;
s1.slice(...m1.indices[1]) === "z";

m1.indices.groups["Z"][0] === 4;
m1.indices.groups["Z"][1] === 5;
s1.slice(...m1.indices.groups["Z"]) === "z";

// capture groups that are not matched return `undefined`:
const m2 = re1.exec("xaaay");
m2.indices[1] === undefined;
m2.indices.groups["Z"] === undefined;
```

## 3 [Top-level await](https://github.com/tc39/proposal-top-level-await)
以前我们使用await时都必须把await包在一个async函数中，现在有了这个特性不需要了，比如我要在模块最前面import另一个模块，就
不要包一个async的自执行函数了，可以直接await
```javascript
const strings = await import(`/i18n/${navigator.language}`);
const connection = await dbConnector();
let jQuery;
try {
  jQuery = await import('https://cdn-a.com/jQuery');
} catch {
  jQuery = await import('https://cdn-b.com/jQuery');
}
```

## 4 [Ergonomic brand checks for Private Fields](https://github.com/tc39/proposal-private-fields-in-in)
检查私有字段是否存在
```javascript
class C {
  #brand;

  #method() {}

  get #getter() {}

  static isC(obj) {
    return #brand in obj && #method in obj && #getter in obj;
  }
}
C.isC(new C()) // true
```

## 5 .at()
支持传入负数来取数组中的值
```javascript
const fruitsArray = ['banana', 'apple', 'orange', 'kiwi'];
console.log(fruitsArray.at(-1))
// Output: kiwi
console.log(fruitsArray[fruitsArray.length -1])
// Output: kiwi
console.log(fruitsArray.at(1))
// Output: apple

const fruit = 'kiwi';
console.log(fruit.at(-1))
// Output: i
```
## 6 Accessible Object.prototype.hasOwnProperty
在Object对象上新增一个方法hasOwn，用来替换Object.prototype.hasOwnProperty这种用法。
目前使用Object.prototype.hasOwnProperty这个方法来检查属性是否在对象中已经非常普遍了，特别是在一些JS库中。常规用法如下
```javascript
let hasOwnProperty = Object.prototype.hasOwnProperty

if (hasOwnProperty.call(object, "foo")) {
  console.log("has property foo")
}
```
但这非常不方便，最方便的是直接obj.hasOwnProperty，但是之所以没有这么用，有以下几个问题
* Object.create(null)创建出来的对象不继承自Object.prototype，所以没这个方法
```javascript
Object.create(null).hasOwnProperty("foo")
// Uncaught TypeError: Object.create(...).hasOwnProperty is not a function
```
* hasOwnProperty 可以被对象重新定义
```javascript
let object = {
  hasOwnProperty() {
    throw new Error("gotcha!")
  }
}

object.hasOwnProperty("foo")
// Uncaught Error: gotcha!
```

这个特性的示例
```javascript
let object = { foo: false }
Object.hasOwn(object, "foo") // true

let object2 = Object.create({ foo: true })
Object.hasOwn(object2, "foo") // false

let object3 = Object.create(null)
Object.hasOwn(object3, "foo") // false
```
## 7 [Class Static Block](https://github.com/tc39/proposal-class-static-block)
推出一个static的块({})语法，用来解决当需要比较复杂的static字段定义赋值的时候
```javascript
// without static blocks:
class C {
  static x = ...;
  static y;
  static z;
}

try {
  const obj = doSomethingWith(C.x);
  C.y = obj.y
  C.z = obj.z;
}
catch {
  C.y = ...;
  C.z = ...;
}

// with static blocks:
class C {
  static x = ...;
  static y;
  static z;
  static {
    try {
      const obj = doSomethingWith(this.x);
      this.y = obj.y;
      this.z = obj.z;
    }
    catch {
      this.y = ...;
      this.z = ...;
    }
  }
}
```
## 8 [Error Cause](https://github.com/tc39/proposal-error-cause)
给error新增了一个cause属性，在抛出错误的时候可以主动设置，把当前的error对象透传出去，从而拿到错误时的context
```javascript
async function doJob() {
  const rawResource = await fetch('//domain/resource-a')
    .catch(err => {
      throw new Error('Download raw resource failed', { cause: err });
    });
  const jobResult = doComputationalHeavyJob(rawResource);
  await fetch('//domain/upload', { method: 'POST', body: jobResult })
    .catch(err => {
      throw new Error('Upload job result failed', { cause: err });
    });
}

try {
  await doJob();
} catch (e) {
  console.log(e);
  console.log('Caused by', e.cause);
}
// Error: Upload job result failed
// Caused by TypeError: Failed to fetch
```



